package com.verbes.drmas.verbesfranais;
/**
 * Created by drmas on 29/12/2017.
 */
public class premiergroup1 {
    // array of questions
    private String textQuestions2 [] = {
            "1. Les enfants ... (frapper - présent) dans les mains.",
            "2. Julie et moi ... (jouer - présent) à la corde à sauter.",
            "3. Vous ... (sauter - présent) par-dessus la barrière.",
            "4. Preston et Cristina ... (accrocher - présent) un tableau au mur.",
            "5. Laura ... (attacher - présent) le chien le temps d'aller chercher le pain.",
            "6. Le facteur ... (trier - présent) le courrier avant de le distribuer.",
            "7. Ils ... (aimer - présent) le chocolat au lait le matin.",
            "8. Tu n' ... (arrêter - présent) pas de crier contre moi.",
            "9. Je me ... (coucher - présent) de bonne heure.",
            "10. Tu ... (lancer - présent) le ballon et tu traverses le terrain.",
            "11. Je (marcher - passé simple) ... dans la rue.",
            "12. Nous (manger - passé simple) ... des fraises.",
            "13. Elles (aimer - passé simple) ... la mer.",
            "14. Tu (tomber - passé simple) ... de la falaise.",
            "15. Il (raconter - passé simple) ... son histoire aux enfants du village.",
            "16. Vous (lancer - passé simple) ... la balle.",
            "17. Elle (gronder - passé simple) ... sa fille.",
            "18. Ils (chanter - passé simple) ... une chanson.",
            "19. Nous (crier - passé simple) ... très fort.",
            "20. Tu (pleurer - passé simple) ... beaucoup.",
            "21. Tu ... (manger - présent) à la maison ce soir ?",
            "22. Que (dessiner - présent) ...-vous aujourd'hui ?",
            "23. Ils ... (jouer - présent) au football depuis 1 heure !",
            "24. Nous ... (danser - présent) la Salsa !",
            "25. Je ... (chanter - présent) au lieu de faire mes devoirs.",
            "26. Pour mon anniversaire je ... (préparer - présent) un gâteau au chocolat !",
            "27. Elle ... (jouer - présent) à la princesse avec ses poupées.",
            "28. Que (cuisiner - présent) ...-vous ce soir ?",
            "29. Je ... (penser - présent) que je vais préparer un rôti !",
            "30. Parfait ! Alors nous ... (dîner - présent) chez vous !",
            "31. Demain matin, tu nous ... (donner - futur simple) de ses nouvelles.",
            "32. Elle ... (crier - futur simple) la bonne réponse à ses partenaires de jeu.",
            "33. Demain matin, vous ... (copier - futur simple) votre nouvelle poésie.",
            "34. Nous vous ... (téléphoner - futur simple) dès notre arrivée au camping.",
            "35. Les invités ... (arriver - futur simple) sûrement avec quelques minutes de retard.",
            "36. Papa ... (garer futur - simple) sa voiture dans l'allée qui mène au garage.",
            "37. Les boucles du chignon ... (tomber - futur simple) dans le dos de la mariée.",
            "38. Je ... (voyager - futur simple) seul en avion dès que j'aurai 12 ans.",
            "39. Les enfants ... (colorier - futur simple) les étoiles avec leur couleur préférée.",
            "40. La petite fille ... (poser - futur simple) son verre de jus de raisin sur la table basse.",
            "41. Tu ... (voyager - passé composé) avec tes parents cette fois-ci ?",
            "42. Les élèves ... (réciter - passé composé) un poème de Victor Hugo.",
            "43. Mes amis et moi ... (organiser - passé composé) une belle fête d'anniversaire.",
            "44. J' ... (expliquer - passé composé) mon projet à toute la classe.",
            "45. Vous ... (rater - passé composé) l'occasion de votre vie !",
            "46. Le professeur ... (regarder - passé composé) l'élève avec admiration.",
            "47. Notre voisine ... (planter - passé composé) des rosiers dans son jardin.",
            "48. J' ... (brosser - passé composé) mes vêtements avant de sortir.",
            "49. Est-ce que vous ... (corriger - passé composé) vos erreurs ?",
            "50. Les joueurs ... (saluer - passé composé) les spectateurs.",
            "51. (partir - passé composé) Il ... en car à 5 heures du matin.",
            "52. (ne pas aller - passé composé) Hier, Hélène et sa mère ... au marché.",
            "53. (s'amuser - passé composé) Ce matin, les petites filles ... avec Sabine.",
            "54. (tomber - passé composé) La semaine dernière, Pierre ... de son vélo.",
            "55. (ne pas se réveiller - passé composé) Marie ... de bonne heure ce matin.",
            "56. (venir - passé composé) Anne et sa sœur ... nous voir mardi dernier.",
            "57. (être - passé composé) Un si joli bouquet m' ... offert, mais qui remercier.",
            "58. (arriver - passé composé) Mon frère et moi ... en retard.",
            "59. (tomber - passé composé) Lucie ... dans les escaliers ce matin.",
            "60. (rentrer - passé composé) Ils ... de vacances hier soir.",
            "61. La semaine dernière, nous ... (visiter - imparait) un parc animalier.",
            "62. Malheureusement, les loups ... (dormir - imparfait) dans leur enclos.",
            "63. Pendant la visite, je ... (penser - imparfait) à mes amis absents.",
            "64. Ma sœur ... (rester - imparfait) sur un grand banc devant la cage aux oiseaux.",
            "65. Vous ... (regarder - imparfait) les pélicans nourrir leurs petits.",
            "66. Tu ... (manger - imparfait) une glace à la vanille en te dirigeant vers le lac.",
            "67. Les enfants ... (lancer - imparfait) du pop-corn aux chèvres.",
            "68. Ma cousine ... (croquer - imparfait) une pomme en regardant les girafes.",
            "69. Vous ... (admirer - imparfait) les serpents et les iguanes.",
            "70. Nous ... (adorer - imparfait) nous rendre dans ce zoo.",
             "71. Où sont les enfants ? Les enfants ... (manger - présent) à la cantine de l'école.",
             "72. Maman ... (regarder - présent) la télévision tous les soirs.",
             "73. Hier, le soleil ... (être - passé composé) brillé toute la journée.",
             "74. Il est acteur de cinéma. Il ... (travailler - présent) à Hollywood",
             "75. Lorsqu'elle était jeune, elle ... (chanter - imparfait) dans une chorale ",
             "76. Nous ... (penser - passé composé) que c'était le mieux",
             "77. Il ... (jeter - passé simple) le papier à la poubelle.",
             "78. La voiture ne ... (démarrer - présent) pas, j'appelle le garagiste.",
             "79. Ils ... (écouter - présent) leur professeur pour réussir leurs examens.",
             "80. (aimer - présent) ...-vous le chocolat?",
            "81. Alors qu'elle ne l'espérait plus, elle ... (avoir - plus que imparfait) un chien pour son anniversaire.",
            "82. elle ... (courir - plus que imparfait) pendant une heure cinquante sans s'arrêter !",
            "83. Nous ... (perdre - plus que imparfait) nos clés, et nous n'arrivions plus à rentrer chez nous.",
            "84. Yohan ... (finir - plus que imparfait) ses devoirs et regardait la télévision.",
            "85. Julie adorait les films de science-fiction; sa mère lui ... (offrir - plus que imparfait) un DVD.",
            "86. Avec sa meilleure amie, Chloé ... (regarder - plus que imparfait) ce qui lui conviendrait le plus.",
            "87. Tom et Nathan ... dans un château, et ils y ... (faire - plus que imparfait) beaucoup de bêtises.",
            "88. À l'école, Fanny ... (apprendre - plus que imparfait) la politesse.",
            "89. Alexandra n' ... (sortir - plus que imparfait) de la France qu'une seule fois.",
            "90. Marine et ses trois amies ... (arriver - plus que imparfait) avant Justin.",
            "91. Ces mots ... (écrire - plus que imparfait passif) avec application. ",
            "92. Quand j' ... (prendre - futur intérieur) ma douche, j'écouterai un bon disque.",
            "93. Paul sera plus serein une fois qu'il ... (passer - futur intérieur) ses examens.",
            "94. Lorsque tu ... (fermer - futur intérieur) les volets, tu allumeras le feu dans la cheminée.",
            "95. Les ouvriers ... (terminer - futur intérieur) le chantier avant la fin de la semaine.",
            "96. Le nombre d'accidents de la route ... (être + réduire) grâce à cette nouvelle mesure.",
            "97. Le tabac l' ... (tuer - futur intérieur) avant qu'il soit à la retraite, s'il continue ainsi.",
            "98. Quand tu ... (avoir - futur intérieur) ton permis de conduire, tu pourras critiquer les conducteurs !",
            "99. Je vous donnerai un autre document quand vous ... (terminer - futur intérieur) l'étude de celui-ci.",
            "100. Marie ... (arriver - futur intérieur) avant ton départ."
    };
    // array of multipe choice for each question
    private String multipeChoice2 [][] =  {
        {"frappent", "frappaient", "frappons"},
        {"jouions", "jouons", "jouerons"},
        {"sautiez", "sauterez", "sautez"},
        {"accrochaient", "accrochent", "accrocheront"},
        {"attache", "attachait", "attacha"},
        {"triera", "trie", "trait"},
        {"aimeront", "aiment", "aimaient"},
        {"arrêtes", "arrêtais", "arrêteras"},
        {"coucherais", "couchais", "couche"},
        {"lançais", "lances", "lanceras"},
        {"marchai", "marchais", "marchait"},
        {"mangeons", "mangeâmes", "mangerons"},
        {"aimèrent", "aimeront", "aiment"},
        {"tombes", "tombas", "tomberas"},
        {"raconte", "racontera", "raconta"},
        {"lancez", "lançâtes", "lancerez"},
        {"grondait", "gronde", "gronda"},
        {"chantèrent", "chantent", "chanteront"},
        {"crierons", "crions", "criâmes"},
        {"pleuras", "pleure", "pleurent"},
        {"manges", "mangeras", "mangeais"},
        {"dessiniez", "dessinez", "dessinerez"},
        {"joueront", "jouaient", "jouent"},
        {"dansions", "dansons", "danserons"},
        {"chante", "chantais", "chanta"},
        {"préparai", "préparerais", "prépare"},
        {"joue", "jouait", "jouera"},
        {"cuisinez", "cuisinent", "cuisinons"},
        {"pensa", "pense", "pensais"},
        {"dînons", "dînerons", "dînez"},
        {"donnera", "donneras", "donnerais"},
        {"criera", "crieras", "crierai"},
        {"copiez", "copiez", "copierez"},
        {"téléphonions", "téléphonerons", "téléphonons"},
        {"arriveront", "arrivaient", "arrivent"},
        {"garera", "garerait", "garera"},
        {"tombent", "tomberont", "tombèrent"},
        {"voyage", "voyagerais", "voyagerai"},
        {"colorieront", "colorièrent", "colorient"},
        {"posere", "posera", "poserait"},
         {"ais voyagé", "avais voyagé", "es voyagé "},
         {"ont récité", "avaient récités", "sont récité"},
         {"avons organisés", "sommes organisé", "avions organisé"},
         {"suis expliqué", "avais expliqué", "ai expliqué"},
         {"aviez ratés", "avez raté", "êtes raté"},
         {"aura regardés", "est regardé", "a regardé"},
         {"a planté", "est planté", "avait planté"},
         {"ai brossé", "avais brossés", "eus brossé"},
         {"aviez corrigés", "avez corrigé", "êtes corrigé"},
         {"auront salués", "ont salué", "sont salué"},
        {"est parti", "a parti", "avait"},
        {"ne sont pas allées", " n’étaient pas allés", "ne ont pas allées"},
        {"s'ont amusées", "se sont amusées", "se sont amusée"},
        {"est tombés", "a tombé", "est tombé"},
        {"ne s'est pas réveillées", "ne s'est pas réveillée", "ne s'est pas réveillés"},
        {"sont venues", "sont venue", "ont venues"},
        {"a été", "est été", "ait été"},
        {"sommes arrivé", "avons arrivés", "sommes arrivés"},
        {"est tombées", "est tombée", "est tombé"},
        {"sont rentrées", "ont rentrés", "sont rentrés"},
        {"visitions", "visitions", "visiterons"},
        {"dormaient", "dorment", "dormiront"},
        {"pensa", "pensais", "pensai"},
        {"restais", "reste", "restait"},
        {"regardez", "regardiez", "regarderez"},
        {"manges", "mangeais", "mangeras"},
        {"lanceront", "lancent", "lançaient"},
        {"croquait", "croque", "croqua"},
        {"admirerez", "admirez", "admiriez"},
        {"adorions", "adorons", "adorâmes"},
        {"mangent", "mange", "mangeaient"},
        {"regardera", "regarde", "regardait"},
        {"a été", "est été", "ait été"},
        {"travaillera", "travaillait", "travaille"},
        {"chantait", "chante", "chanta"},
        {"avons pensés", "avons pensé", "avions pensée"},
        {"jette", "jettait", "jeta"},
        {"démarra", "démarre", "démarrait"},
        {"écoutent", "écoutaient", "écouteront"},
        {"Aimez", "Aimerez", "Aimiez"},
        {"avait eut", "avait eu", "avait eus"},
        {"avait couru", "avait courus", "avait courut"},
        {"avons perdu", "avions perdu", "aurons perdu"},
        {"avait fini", "avait finit", "avait finis"},
        {"avait offert", "avait offerts", "avait offere"},
        {"avait regardés", "avaient regardé", "étaient regardé"},
        {"avaient fait", "étaient fait", "ont fait"},
        {"était appris", "eut appris", "avait appris"},
        {"était sorties", "était sorti", "était sortie"},
        {"étaient arrivées", "étaient arrivée", "étaient arrivés"},
        {"avaient été écrites", "avaient été écrit", "avaient été écrits"},
        {"aurait pris", "aurai pris", "aurais pris"},
        {"aura passés", "aurait passé", "aura passé"},
        {"auras fermé", "aurait fermé", "aura fermés"},
        {"auront terminées", "auront terminé", "aurons terminés"},
        {"aura été réduit", "aura est réduit", "aura été réduis"},
        {"aura tuées", "aura tué", "aura tués"},
        {"auras eut", "aurais eu", "auras eu"},
        {"aurez terminé", "aurez terminés", "aurez terminées"},
        {"sera arrivé", "aura arrivée", "sera arrivées"}

    };

    // array of correct answers - in the same order as array of questions
    private String mCorrectAnswers2[] = {
            "frappent", "jouons", "sautez", "accrochent", "attache", "trie", "aiment", "arrêtes", "couche", "lances",
            "marchai", "mangeâmes", "aimèrent", "tombas", "raconta", "lançâtes", "gronda", "chantèrent", "criâmes", "pleuras",
            "manges", "dessinez", "jouent", "dansons", "chante", "prépare", "joue", "cuisinez", "pense", "dînons",
            "donneras", "criera", "copierez", "téléphonerons", "arriveront", "garera", "tomberont", "voyagerai", "colorieront", "posera",
            "as voyagé", "ont récité", "avons organisé", "ai expliqué", "avez raté", "a regardé", "a planté", "ai brossé", "avez corrigé", "ont salué",
            "est parti", "ne sont pas allées", "se sont amusées", "est tombé", "ne s'est pas réveillée", "sont venues", "a été", "sommes arrivés", "est tombée", "sont rentrés",
            "visitions", "dormaient", "pensais", "restait", "regardiez", "mangeais", "lançaient", "croquait", "admiriez", "adorions",
            "mangent", "regarde", "a été", "travaille", "chantait", "avons pensé", "jeta", "démarre", "écoutent", "Aimez",
            "avait eu", "avait couru", "avions perdu", "avait fini", "avait offert", "avait regardé", "avaient fait", "avait appris", "était sorti", "étaient arrivées",
            "avaient été écrits", "aurai pris", "aura passé", "auras fermé", "auront terminé", "aura été réduit", "aura tué", "auras eu", "aurez terminé", "sera arrivée" };

    // method return numbers - in the same order as array of questions
    public int getLength() {return textQuestions2.length; }

    //method return question from array textQueston[] based on array index
    public String getQuestions(int a){
        String question = textQuestions2[a];
        return question;
    }
    // method return a single multipe choice item for question based on array index,
    // based on number of miltipe choice in the list - 1, 2, 3, or 4 as an arqument
    public String getChoice(int index, int num){
        String choice0 = multipeChoice2[index][num-1];
        return choice0;
    }
    // method returns correct answer for the question based on array index
    public String getCorrectAnswer(int a){
        String answer = mCorrectAnswers2[a];
        return answer;
    }
}
