package com.verbes.drmas.verbesfranais;

/**
 * Created by drmas on 29/12/2017.
 */

public class troisgroup3 {

    // array of questions
    private String textQuestions2 [] = {
            "1. Depuis quelques temps, tu me ... (battre - présent) toujours aux échecs.",
            "2. Je ... (perdre - présent) beaucoup de temps à écouter tes bêtises.",
            "3. Nous ... (coudre - présent) des perles sur une robe de mariée.",
            "4. Tu ... (vendre - présent) ton pavillon, m'a-t-on dit !",
            "5. Pourquoi pleures-tu ? ... (vouloir - présent) tu un bonbon ?",
            "6. ... (joindre - présent) vous à nous! Nous serons ravis de passer la soirée avec vous.",
            "7. Les enfants ... (entendre - présent) cette leçon pour la première fois.",
            "8. Elle ... (boire - présent) beaucoup d'eau pour se réhydrater après la longue marche. ",
            "9.  ... (apprendre - présent) tu tes leçons avant de faire les exercices? Je te le conseille fortement.",
            "10. Je vous remercie d'avoir patienté. Vous ... (pouvoir - présent) y aller dès maintenant.",
            "11. Tu ... (descendre - présent) la rivière.",
            "12. Tu ... (rejoindre - présent) le barrage.",
            "13. Tu ... (pouvoir - présent) aller dans l'île.",
            "14. Je ... (voiloir - présent) t'accompagner.",
            "15. La barque ne ... (pouvoir - présent) pas passer.",
            "16. Tu ... (découvrir - présent) un beau paysage.",
            "17. Tu ... (voiloir - présent) le photographier.",
            "18. La pie ... (construire - présent) son nid dans le pommier",
            "19. Romain ... (courir - présent) après Ludovic.",
            "20. Tu ... (descendre - présent) l'escalier.",
            "21. Nous ... (partir - passé composé) en Thaïlande l'été dernier avec les enfants.",
            "22. Ma nièce m' ... (offrir - passé composé) un joli bracelet qui va bien avec mon collier.",
            "23. Tu ... (vouloir - passé composé) faire de la danse mais tu ne savais pas que ce serait aussi difficile.",
            "24. Elle ... (devenir - passé composé) une enseignante aimée de tous ses élèves.",
            "25. Les explorateurs ... (découvrir - passé composé) un cimetière d'animaux près d'ici.",
            "26. Tu ... (boire - passé composé) un verre de jus d'orange ce matin.",
            "27. Mes cousines ... (sortir - passé composé) en ville pour acheter des robes d'été.",
            "28. J' ... (attendre - passé composé) l'arrivée du train avec impatience.",
            "29. Mes grands-parents ... (revenir - passé composé) vivre à la maison le temps de leurs travaux de rénovation.",
            "30. Le professeur ... (écrire - passé composé) au tableau la liste des candidats à l'élection des délégués de classe.",
            "31. Voyant le chaton sur le canapé, je ... (faire - passé simple) un grand sourire.",
            "32. Tu appris tes leçons, puis tu ... (vouloir - passé simple) faire de la lecture.",
            "33. Lorsque l'enfant ... (reconnaître - passé simple) sa mère, il se jeta immédiatement dans ses bras.",
            "34. Malgré des pluies abondantes, jamais nous ne ... (revoir - passé simple) une telle crue.",
            "35. Après avoir dégagé le poisson de l'hameçon, vous le ... (mettre - passé simple) dans le seau.",
            "36. La forte fièvre ne cédant pas, les parents se ... (rendre - passé simple) à l'hôpital avec leur enfant malade.",
            "37. Après les présentations, l'hôte ... (introduire - passé composé) les visiteurs dans le salon.",
            "38. Afin de l'aider à franchir l'obstacle, il lui ... (tendre - passé composé) la main.",
            "39. Dès l'entrée du train en gare, d'autres voyageurs ... (venir - passé composé) se joindre à nous sur le quai.",
            "40. Quand nous entendîmes les cris, nous ... (venir - passé composé) secourir cette dame.",
            "41. Tu (battre - présent) ... la semelle en attendant le bus.",
            "42. Dans l'enclos l'antilope (paître - présent) ... tranquillement.",
            "43. Tu (entendre - présent) ... la sirène des pompiers.",
            "44. Vous (peindre - présent) ... ces dessins pour l'exposition.",
            "45. Escartefigue (fendre - présent) ... le cœur de César.",
            "46. L'actrice (feindre - présent) ... de tomber dans les pommes.",
            "47. C'est normal ; le sel (se dissoudre - présent) ... dans l'eau.",
            "48. Vous (se taire - présent) ... par crainte de dire une bêtise.",
            "49. L'homme (acquérir - présent) ... la connaissance en travaillant.",
            "50. Son corps (gésir - présent) ... maintenant sur la plage.",
            "51. Chaque matin, Hugo ... (aller - imparfait) promener son chien.",
            "52. Nous ... (dire -imparfait) bonjour tous les jours à notre voisine.",
            "53. Les élèves ... (faire - imparfait) leurs exercices de math très facilement.",
            "54. En colo, nous ... (pouvoir - imparfait) jouer comme il nous plaisait.",
            "55. Pour partir en vacances, je ... (prendre - imparfait) toujours le train.",
            "56. Tu ... (savoir - imparfait) s'il allait faire beau en regardant la couleur du ciel.",
            "57. Nous ... (voir - imparfait) le facteur tous les jours en partant à l'école.",
            "58. Les oiseaux ... (venir - imparfait) toujours manger toutes les cerises de notre cerisier.",
            "59. Petite, je ... (vouloir - imparfait) devenir vétérinaire.",
            "60. Il ... (être - imparfait) aussi grand qu'une girafe.",
            "61. Attends ! La colle ... (durcir - futur simple) en séchant.",
            "62. Là-bas, tu te ... (se plaindre - futur simple) de la chaleur étouffante.",
            "63. Si nous sommes doués, nous ... (envoyer - futur simple) le ballon entre les poteaux.",
            "64. Maintenant, vous ne ... (confondre - futur simple) plus les pêches et les brugnons.",
            "65. Les journalistes ... (faire - futur simple) le point sur les derniers événements.",
            "66. Le cavalier ne ... (pouvoir - futur simple) pas maîtriser sa monture s'il monte ainsi !",
            "67. Au goûter, les enfants ... (boire - futur simple) un verre de jus de fruits.",
            "68. La semaine prochaine, le kilogramme de cerises ... (valoir - futur simple) trois euros.",
            "69. Malgré tes efforts, tu ne ... (parvenir - futur simple) pas à rétablir la situation.",
            "70. Dans dix minutes, le taxi ... (être - futur simple) au pied de l'immeuble.",
            "71. Nous (devoir - passé composé) ... partir plus tôt.",
            "72. Je ne (concevoir - imparfait) ... pas de rater ces examens.",
            "73. Nous (décevoir - passé simple) ... nos parents par notre attitude.",
            "74. D'après sa réponse, je (percevoir - passé simple) ... son mécontentement.",
            "75. Aussitôt que j'eus dépassé la rue, je m' (apercevoir - passé simple) ... que je m'étais trompé de chemin.",
            "76. Il faut que tu (recevoir - subjonctif présent) ... ces informations afin de traiter correctement le dossier.",
            "77. Il fallait que tu (devoir - subjonctif imparfait) ... autant d'argent pour accepter ce travail lourd et difficile.",
            "78. La lecture de cette revue me (décevoir - présent) ....",
            "79. Par une lecture attentive, vous (percevoir - futur simple) ... les nuances de son discours.",
            "80. Nous n' (apercevoir - futur simple) ... pas la lune lors de nos observations vu la météo.",
            "81. Je ... (descendre - présent) de la montagne pour rejoindre le chalet.",
            "82. Je ... (tenir - présent) un stylo, j'attends ta dictée.",
            "83. Il ... (pouvoir - présent) aller à Paris au mois de mars avec son patron.",
            "84. Tu ... (pouvoir - présent) aller jouer avec tes amis si tes devoirs sont terminés.",
            "85. L'oiseau ... (construire - présent) son nid sous mon toit.",
            "86. Nous ... (descendre - présent) le torrent à vive allure en espérant trouver une solution avant les chutes.",
            "87. Vous ... (vouloir - présent) bien m'aider ? Je n'arrive pas à ouvrir cette porte.",
            "88. Ils ... (descendre - présent) les escaliers en silence, conformément au règlement de l'école.",
            "89. Il ... (rejoindre - présent) le passage à niveau puis traverse la voie ferrée avec le chef de gare.",
            "90. Chaque soir tu ... (rejoindre - présent) ton père au bureau et vous m'attendez.",
            "91. Je ... (aller - présent) à la piscine.",
            "92.  .... (Pouvoir - présent) - tu me répondre ?",
            "93. Il ... (boire - présent) sa grenadine sans rien dire.",
            "94. Vous ... (commettre - présent) une grave erreur !",
            "95. Nous ... (prendre - présent) notre temps.",
            "96. Ils ne ... (comprendre - présent) pas la question.",
            "97. Les gâteaux ne ... (cuire - présent) pas si rapidement !",
            "98. Ne ... (croire - présent) pas tout ce qu'on vous dit !",
            "99. Nous ne ... (craindre - présent) plus rien ici.",
            "100. J' ... (enfreindre - présent) la loi en faisant ça."

    };

    // array of multipe choice for each question
    private String multipeChoice2 [][] =  {
            {"bats", "bat", "batts"},
            {"perds", "perdra", "perd"},
            {"coudons", "cousons", "coudions"},
            {"vend", "vendes", "vends"},
            {"veux", "veut", "voulu"},
            {"joindrez", "joignez", "joigniez"},
            {"entendaient", "entendent", "entendront"},
            {"bois", "bu", "boit"},
            {"apprend", "apprends", "apprendras"},
            {"pouvez", "pourrez", "pu"},
            {"descend", "descends", "descendu"},
            {"rejoint", "rejoints", "rejoins"},
            {"peut", "peux", "pu"},
            {"veux", "veut", "voulu"},
            {"peux", "pu", "peut"},
            {"découvres", "découvre", "découvrit"},
            {"voulu", "veux", "veut"},
            {"construis", "construit", "construits"},
            {"courts", "court", "couru"},
            {"descend", "descendu", "descends"},
            {"sommes partis", "avons partis", "sommes parties"},
            {"a offerte", "a offert", "est offert"},
            {"as voulus", "as voulut", "as voulu"},
            {"est devenu", "est devenue", "a devenue"},
            {"ont découvert", "ont découverte", "ont découverts"},
            {"as bus", "as bu", "as but"},
            {"sont sortie", "sont sortis", "sont sorties"},
            {"ai attendit", "ai attendus", "ai attendu"},
            {"sont revenus", "sont revenues", "sont reveut"},
            {"a écrits", "a écrit", "a écris"},
            {"fis", "fais", "fits"},
            {"voulu", "voulus", "voulut"},
            {"reconnus", "reconnue", "reconnut"},
            {"revîmons", "revîmens", "revîmes"},
            {"mîtes", "mis", "mîmes"},
            {"rendu", "rendirent", "renduent"},
            {"introduisis", "introduit", "introduisit"},
            {"tendis", "tendu", "tendit"},
            {"venu", "vinrent", "viennent"},
            {"vînmes", "venues", "venons"},
            {"bats", "battu", "bates"},
            {"paîtra", "paît", "paîts"},
            {"entend", "entendu", "entends"},
            {"peignez", "peigniez", "peindrez"},
            {"fendu", "fends", "fend"},
            {"feint", "feints", "feinte"},
            {"se dissouts", "se dissout", "se dissoute"},
            {"vous taises", "vous taisez", "vous taisiez"},
            {"acquiera", "adquieres", "acquiert"},
            {"gisait", "gît", "gis"},
            {"allais", "allait", "allaient"},
            {"disons", "disions", "dissions"},
            {"faits", "font", "faisaient"},
            {"pourrons", "pouvons", "pouvions"},
            {"prenais", "prenait", "prennes"},
            {"savait", "savais", "savaient"},
            {"voyons", "voiions", "voyions"},
            {"viennes", "venaient", "venu"},
            {"voulait", "voulais", "voulaient"},
            {"étais", "était", "étaient"},
            {"durciras", "durcit", "durcira"},
            {"plaindras", "plaindrai", "plaindra"},
            {"enverront", "enverrons", "enverrens"},
            {"confondriez", "confondrez", "confondez"},
            {"feront", "fera", "ferons"},
            {"pourra", "pourras", "pourrai"},
            {"boirons", "boivent", "boiront"},
            {"vaudrai", "vaudra", "vaudras"},
            {"parviendra", "parviendrai", "parviendras"},
            {"sera", "serai", "seras"},
            {"avions dû", "avons dût", "avons dû"},
            {"concevais", "conceve", "concevait"},
            {"déçue", "déçûmes", "déçût"},
            {"perçut", "perçus", "perçues"},
            {"aperçus", "aperçut", "aperçues"},
            {"reçoive", "reçoives", "reçoivent"},
            {"dusse", "dusset", "dusses"},
            {"déçoit", "déçois", "déçoive"},
            {"percevras", "percevrez", "percevra"},
            {"apercevront", "apercevrons", "apercevrez"},
            {"descend", "descends", "descende"},
            {"tiens", "tient", "tienne"},
            {"peux", "peut", "pu"},
            {"peux", "pus", "peut"},
            {"construis", "construit", "construits"},
            {"descendont", "descendens", "descendons"},
            {"voulez", "voules", "voule"},
            {"descendens", "descendent", "descendents"},
            {"rejoins", "rejoint", "rejoints"},
            {"rejoint", "rejoins", "rejoints"},
            {"vais", "va", "vait"},
            {"Peut", "Peux", "Peus"},
            {"boit", "boie", "bois"},
            {"commettez", "commettes", "commettent"},
            {"prenont", "prenons", "prenent"},
            {"comprennens", "comprennent", "comprennont"},
            {"cuisens", "cuisents", "cuisent"},
            {"croyes", "croyez", "croye"},
            {"craignont", "craignons", "craignonts"},
            {"enfreint", "enfreions", "enfreins"}




    };

    // array of correct answers - in the same order as array of questions
    private String mCorrectAnswers2[] = {
     "bats", "perds", "cousons", "vends", "veux", "joignez", "entendent", "boit", "apprends", "pouvez",
    "descends", "rejoins", "peux", "veux", "peut", "découvres", "veux", "construit", "court","descends",
    "sommes partis", "a offert", "as voulu", "est devenue", "ont découvert", "as bu", "sont sorties", "ai attendu", "sont revenus", "a écrit",
     "fis", "voulus", "reconnut", "revîmes", "mîtes", "rendirent", "introduisit", "tendit", "vinrent", "vînmes",
            "bats", "paît", "entends", "peignez", "fend", "feint", "se dissout", "vous taisez", "acquiert", "gît",
            "allait", "disions", "faisaient", "pouvions", "prenais", "savais", "voyions", "venaient", "voulais", "était",
            "durcira", "plaindras", "enverrons", "confondrez", "feront", "pourra", "boiront", "vaudra", "parviendras", "sera",
            "avons dû", "concevais", "déçûmes", "perçus", "aperçus", "reçoives", "dusses", "déçoit", "percevrez", "apercevrons",
            "descends", "tiens", "peut", "peux", "construit", "descendons", "voulez", "descendent", "rejoint", "rejoins",
            "vais", "Peux", "boit", "commettez", "prenons", "comprennent", "cuisent", "croyez","craignons","enfreins"};

    // method return numbers - in the same order as array of questions
    public int getLength() {return textQuestions2.length; }

    //method return question from array textQueston[] based on array index
    public String getQuestions(int a){
        String question = textQuestions2[a];
        return question;
    }
    // method return a single multipe choice item for question based on array index,
    // based on number of miltipe choice in the list - 1, 2, 3, or 4 as an arqument
    public String getChoice(int index, int num){
        String choice0 = multipeChoice2[index][num-1];
        return choice0;
    }
    // method returns correct answer for the question based on array index
    public String getCorrectAnswer(int a){
        String answer = mCorrectAnswers2[a];
        return answer;
    }
}
